algoritmo "obter nome e idade de N pessoas"
// Função :
// Autor :
// Data : 20/09/2023
// Seção de Declarações 
var
       nome             : caracter
       idade            : inteiro
inicio
// Seção de Comandos 
   escreval ("Informe o nome (digite 0 para terminar): ")
   leia (nome)
   enquanto (nome <> "0") faca
   
         escreval ("Informe a idade: ")
         leia (idade)
         escreval ("Informe o nome (digite 0 para terminar): ")
         leia (nome)

   fimenquanto
fimalgoritmo
