Algoritmo "exemplo 1 - Olá"
// Disciplina   : EDLP
// Professor   : Rafael
// Descrição   : Programa que diz olá
// Autor(a)    : Rafael
// Data atual  : 11/08/2023
Var
// Seção de Declarações das variáveis 
    nome            : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     escreval ("Olá mundo!!!")
     
     nome <- "Maria"

     escreval ("Meu nome é ", nome)

Fimalgoritmo