algoritmo "Informar vários nomes"
// Função :
// Autor :
// Data : 15/09/2023
// Seção de Declarações 
var
     nome                       : caracter
     cont, idade                : inteiro
inicio
// Seção de Comandos 

   cont <- 1
   enquanto (cont <= 20) faca

      escreval ("Entre com o ", cont, "º nome: ")
      leia (nome)
      escreval ("Entre com a idade: ")
      leia (idade)
      
      cont <- cont + 1
      
   fimenquanto
   
fimalgoritmo
