algoritmo "média aritmética"
// Função :
// Autor :
// Data : 16/08/2023
// Seção de Declarações 
var
      nota1, nota2, nota3, media    : real
inicio
// Seção de Comandos 
      escreval ("Digite a primeira nota: ")
      leia (nota1)
      escreval ("Digite a segunda nota: ")
      leia (nota2)
      escreval ("Digite a terceira nota: ")
      leia (nota3)
      
      media <- (nota1 + nota2 + nota3) / 3
      
      escreval ("A média é ", media)
fimalgoritmo
