algoritmo "verifica número"
// Função :
// Autor :
// Data : 18/08/2023
// Seção de Declarações 
var
       numero           : inteiro
inicio
// Seção de Comandos 
   escreval ("Informe um número: ")
   leia (numero)
   
   se (numero = 0) entao
   
       escreval ("O número informado é igual a 0")
       
   senao
   
       escreval ("O número informado é diferente de 0")
       
   fimse
fimalgoritmo
